name = "Template"
author = "Author"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8df0e9a39339c72a7c7da2b37746238848f4837bfef928a299b96ddb37da8389"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
