name = "Template"
author = "Author"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b78ba202584c0a3a6af159c7ead19677d85bd098ab3a017445bfa6f66988190d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
