name = "Template"
author = "Author"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "278a11d4960f23c93c767dd56ac5410356b4dee41dba280818250136c62eb512"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.227"
